@url = http://localhost:3000/validate/
 POST {{url}}
 Content-Type: application/json


{
	"items": [{
			"Id": "1",
			"PostedBy": "Jane Doe",
			"category": "Some Category",
			"UserName": "Me",
			"effectiveDate": "2022-09-30",
			"reviewerId": "Mon"
		},
        {
			"Id": "2",
			"PostedBy": "Jon Doe",
			"category": "Category 2",
			"UserName": "Someone else",
			"effectiveDate": "2022-09-30"
			
		}
        
    ]
}