@url = http://localhost:3000/validate2/
 POST {{url}}
 Content-Type: application/json


[{
			"Id": "2",
			"PostedBy": "Jane Doe",
			"category": "Some Category",
			"UserName": "Me",
			"effectiveDate": "2022-09-30",
			"reviewerId": 1
		},
        {
			"Id": "2",
			"PostedBy": "Jon Doe",
			"category": "Category 2",
			"UserName": "Someone else",
			"effectiveDate": "2022-09-30",
			"reviewerId": 2
			
		}
        
    ]
